services:
  pipeline:
    build:
      context: .
      dockerfile: application/pipeline/Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - ${PWD}/common:/app/common
      - ${PWD}/application/pipeline:/app/application/pipeline
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
    depends_on:
      - redis
    networks:
      - marly_default

  extraction:
    build:
      context: .
      dockerfile: application/extraction/Dockerfile
    volumes:
      - ${PWD}/common:/app/common
      - ${PWD}/application/extraction:/app/application/extraction
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
    depends_on:
      - redis
    networks:
      - marly_default

  transformation:
    build:
      context: .
      dockerfile: application/transformation/Dockerfile
    volumes:
      - ${PWD}/common:/app/common
      - ${PWD}/application/transformation:/app/application/transformation
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
    depends_on:
      - redis
    networks:
      - marly_default

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - marly_default

networks:
  marly_default:
    name: marly_default
